export const metadata = {
  title: "Contact Page",
  description: "Generated by create next app",
};

export default function ContactLayout({ children }) {
  return (
    <main>
      <h1>Ich komme aus Contact Layout</h1>
      {children}
    </main>
  );
}
